// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFmHHedSm8BFhkOCPNQNFcnm3rNrn0LHU',
    appId: '1:380276777750:web:00ca1dc50e78bcc7836637',
    messagingSenderId: '380276777750',
    projectId: 'signspeak-199c8',
    authDomain: 'signspeak-199c8.firebaseapp.com',
    storageBucket: 'signspeak-199c8.firebasestorage.app',
    measurementId: 'G-VKB6E0PV3R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7zMuDX30GF9qpWAgMXg9GgJWohDq0v9k',
    appId: '1:380276777750:android:c2e2e3e58763fdce836637',
    messagingSenderId: '380276777750',
    projectId: 'signspeak-199c8',
    storageBucket: 'signspeak-199c8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3BWYtBKBy_4pkH9Cw8t_JXYPEY8JIUXU',
    appId: '1:380276777750:ios:3dcdd9139d8501ff836637',
    messagingSenderId: '380276777750',
    projectId: 'signspeak-199c8',
    storageBucket: 'signspeak-199c8.firebasestorage.app',
    iosBundleId: 'com.example.signspeak',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3BWYtBKBy_4pkH9Cw8t_JXYPEY8JIUXU',
    appId: '1:380276777750:ios:3dcdd9139d8501ff836637',
    messagingSenderId: '380276777750',
    projectId: 'signspeak-199c8',
    storageBucket: 'signspeak-199c8.firebasestorage.app',
    iosBundleId: 'com.example.signspeak',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDFmHHedSm8BFhkOCPNQNFcnm3rNrn0LHU',
    appId: '1:380276777750:web:245ee6e793dd2b89836637',
    messagingSenderId: '380276777750',
    projectId: 'signspeak-199c8',
    authDomain: 'signspeak-199c8.firebaseapp.com',
    storageBucket: 'signspeak-199c8.firebasestorage.app',
    measurementId: 'G-PST5QCJCS7',
  );
}
